//
//  StreamCloudStyles.m
//  StreamCloud
//
//  Created by Peter Amende on 24.06.14.
//  Copyright (c) 2014 Call a Nerd. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StreamCloudStyles.h"


@implementation StreamCloudStyles

#pragma mark Cache

static NSColor* _orangeLight = nil;
static NSColor* _orangeMedium = nil;
static NSColor* _orangeDark = nil;
static NSColor* _grayMedium = nil;
static NSColor* _grayDark = nil;
static NSColor* _grayLight = nil;
static NSColor* _artistLabelColor = nil;
static NSColor* _durationLabelColor = nil;

static NSGradient* _orangeGradient = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _orangeLight = [NSColor colorWithCalibratedRed: 1 green: 0.545 blue: 0 alpha: 1];
    _orangeMedium = [NSColor colorWithCalibratedRed: 1 green: 0.416 blue: 0 alpha: 1];
    _orangeDark = [NSColor colorWithCalibratedRed: 1 green: 0.282 blue: 0 alpha: 1];
    _artistLabelColor = _orangeDark;
    _grayMedium = [NSColor colorWithCalibratedRed: 0.298 green: 0.318 blue: 0.329 alpha: 1];
    _durationLabelColor = _grayMedium;
    _grayDark = [NSColor colorWithCalibratedRed: 0.2 green: 0.2 blue: 0.2 alpha: 1];
    _grayLight = [NSColor colorWithCalibratedRed: 0.91 green: 0.91 blue: 0.91 alpha: 1];

    // Gradients Initialization
    _orangeGradient = [NSGradient.alloc initWithStartingColor: StreamCloudStyles.orangeDark endingColor: StreamCloudStyles.orangeLight];

}

#pragma mark Colors

+ (NSColor*)orangeLight { return _orangeLight; }
+ (NSColor*)orangeMedium { return _orangeMedium; }
+ (NSColor*)orangeDark { return _orangeDark; }
+ (NSColor*)grayMedium { return _grayMedium; }
+ (NSColor*)grayDark { return _grayDark; }
+ (NSColor*)grayLight { return _grayLight; }
+ (NSColor*)artistLabelColor { return _artistLabelColor; }
+ (NSColor*)durationLabelColor { return _durationLabelColor; }

#pragma mark Gradients

+ (NSGradient*)orangeGradient { return _orangeGradient; }

#pragma mark Drawing Methods

+ (void)drawPlayPauseButtonWithFrame: (NSRect)frame playing: (BOOL)playing;
{
    //// Color Declarations
    NSColor* fakeClearColor = [NSColor colorWithCalibratedRed: 1 green: 1 blue: 1 alpha: 0];

    //// Variable Declarations
    NSColor* playFillColor = playing ? fakeClearColor : StreamCloudStyles.grayDark;
    NSColor* pauseFillColor = playing ? StreamCloudStyles.grayDark : fakeClearColor;


    //// Subframes
    NSRect group4 = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame));


    //// Group 4
    {
        //// Bezier 8 Drawing
        NSBezierPath* bezier8Path = NSBezierPath.bezierPath;
        [bezier8Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.00000 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.22292 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.00000 * NSWidth(group4), NSMinY(group4) + 0.77708 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.00000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.00000 * NSWidth(group4), NSMinY(group4) + 0.22292 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.22292 * NSWidth(group4), NSMinY(group4) + 0.00000 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 1.00000 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.77708 * NSWidth(group4), NSMinY(group4) + 0.00000 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 1.00000 * NSWidth(group4), NSMinY(group4) + 0.22292 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 1.00000 * NSWidth(group4), NSMinY(group4) + 0.77708 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.77708 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4))];
        [bezier8Path closePath];
        [bezier8Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.04167 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.24583 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.04167 * NSWidth(group4), NSMinY(group4) + 0.24583 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.95833 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.04167 * NSWidth(group4), NSMinY(group4) + 0.75417 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.24583 * NSWidth(group4), NSMinY(group4) + 0.95833 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.95833 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.75417 * NSWidth(group4), NSMinY(group4) + 0.95833 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.95833 * NSWidth(group4), NSMinY(group4) + 0.75417 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.95833 * NSWidth(group4), NSMinY(group4) + 0.24583 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.75417 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4))];
        [bezier8Path closePath];
        [bezier8Path setMiterLimit: 4];
        [bezier8Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier8Path fill];


        //// Bezier 9 Drawing
        NSBezierPath* bezier9Path = NSBezierPath.bezierPath;
        [bezier9Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.75625 * NSWidth(group4), NSMinY(group4) + 0.52500 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.39375 * NSWidth(group4), NSMinY(group4) + 0.74583 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.72917 * NSWidth(group4), NSMinY(group4) + 0.54167 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.41042 * NSWidth(group4), NSMinY(group4) + 0.73542 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.72292 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.37292 * NSWidth(group4), NSMinY(group4) + 0.75833 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.74167 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.27917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.70625 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.30208 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.39375 * NSWidth(group4), NSMinY(group4) + 0.25625 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.25625 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.37708 * NSWidth(group4), NSMinY(group4) + 0.24583 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.75833 * NSWidth(group4), NSMinY(group4) + 0.47917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.41667 * NSWidth(group4), NSMinY(group4) + 0.27083 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.73750 * NSWidth(group4), NSMinY(group4) + 0.46667 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.75625 * NSWidth(group4), NSMinY(group4) + 0.52500 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.77500 * NSWidth(group4), NSMinY(group4) + 0.48750 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.77500 * NSWidth(group4), NSMinY(group4) + 0.51250 * NSHeight(group4))];
        [bezier9Path closePath];
        [bezier9Path setMiterLimit: 4];
        [bezier9Path setWindingRule: NSEvenOddWindingRule];
        [playFillColor setFill];
        [bezier9Path fill];


        //// Bezier 6 Drawing
        NSBezierPath* bezier6Path = NSBezierPath.bezierPath;
        [bezier6Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.39792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.35208 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.32917 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.35208 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.33125 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.39792 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.42083 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.39792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.41875 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier6Path closePath];
        [bezier6Path setMiterLimit: 4];
        [bezier6Path setWindingRule: NSEvenOddWindingRule];
        [pauseFillColor setFill];
        [bezier6Path fill];


        //// Bezier 7 Drawing
        NSBezierPath* bezier7Path = NSBezierPath.bezierPath;
        [bezier7Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.64792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.60208 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.57917 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.60208 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.58125 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.64792 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.67083 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.64792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.66875 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier7Path closePath];
        [bezier7Path setMiterLimit: 4];
        [bezier7Path setWindingRule: NSEvenOddWindingRule];
        [pauseFillColor setFill];
        [bezier7Path fill];
    }
}

+ (void)drawNextButtonWithFrame: (NSRect)frame;
{


    //// Subframes
    NSRect group2 = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame) + 0.1, NSHeight(frame));


    //// Group 2
    {
        //// Bezier 3 Drawing
        NSBezierPath* bezier3Path = NSBezierPath.bezierPath;
        [bezier3Path moveToPoint: NSMakePoint(NSMinX(group2) + 0.80083 * NSWidth(group2), NSMinY(group2) + 0.54583 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.07884 * NSWidth(group2), NSMinY(group2) + 0.98750 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.74689 * NSWidth(group2), NSMinY(group2) + 0.57917 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.11203 * NSWidth(group2), NSMinY(group2) + 0.96667 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.94167 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.03734 * NSWidth(group2), NSMinY(group2) + 1.01250 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.97917 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.05833 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.90833 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.10417 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.07884 * NSWidth(group2), NSMinY(group2) + 0.01250 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.01250 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.04564 * NSWidth(group2), NSMinY(group2) + -0.00833 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.80083 * NSWidth(group2), NSMinY(group2) + 0.45417 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.12448 * NSWidth(group2), NSMinY(group2) + 0.04167 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.76349 * NSWidth(group2), NSMinY(group2) + 0.42917 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.80083 * NSWidth(group2), NSMinY(group2) + 0.54583 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.83817 * NSWidth(group2), NSMinY(group2) + 0.47083 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.83817 * NSWidth(group2), NSMinY(group2) + 0.52500 * NSHeight(group2))];
        [bezier3Path closePath];
        [bezier3Path setMiterLimit: 4];
        [bezier3Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier3Path fill];


        //// Bezier 4 Drawing
        NSBezierPath* bezier4Path = NSBezierPath.bezierPath;
        [bezier4Path moveToPoint: NSMakePoint(NSMinX(group2) + 0.91701 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.91667 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.87137 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.96250 * NSHeight(group2))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.08333 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.91701 * NSWidth(group2), NSMinY(group2) + 0.00000 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.03750 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.87137 * NSWidth(group2), NSMinY(group2) + 0.00000 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.08333 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.96266 * NSWidth(group2), NSMinY(group2) + 0.00000 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.03750 * NSHeight(group2))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.91667 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.91701 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.96250 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.96266 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2))];
        [bezier4Path closePath];
        [bezier4Path setMiterLimit: 4];
        [bezier4Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier4Path fill];
    }
}

+ (void)drawPreviousButtonWithFrame: (NSRect)frame;
{


    //// Subframes
    NSRect group = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame));


    //// Group
    {
        //// Bezier Drawing
        NSBezierPath* bezierPath = NSBezierPath.bezierPath;
        [bezierPath moveToPoint: NSMakePoint(NSMinX(group) + 0.92083 * NSWidth(group), NSMinY(group) + 0.99167 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.19583 * NSWidth(group), NSMinY(group) + 0.55000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.87500 * NSWidth(group), NSMinY(group) + 0.96250 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.23333 * NSWidth(group), NSMinY(group) + 0.57500 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.19583 * NSWidth(group), NSMinY(group) + 0.45417 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.16250 * NSWidth(group), NSMinY(group) + 0.52917 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.15833 * NSWidth(group), NSMinY(group) + 0.47500 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.92083 * NSWidth(group), NSMinY(group) + 0.01250 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.25000 * NSWidth(group), NSMinY(group) + 0.42083 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.88750 * NSWidth(group), NSMinY(group) + 0.03333 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.05833 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.96250 * NSWidth(group), NSMinY(group) + -0.01250 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.02083 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.94167 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.09167 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.89583 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.92083 * NSWidth(group), NSMinY(group) + 0.99167 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.98750 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.95417 * NSWidth(group), NSMinY(group) + 1.01250 * NSHeight(group))];
        [bezierPath closePath];
        [bezierPath setMiterLimit: 4];
        [bezierPath setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        NSBezierPath* bezier2Path = NSBezierPath.bezierPath;
        [bezier2Path moveToPoint: NSMakePoint(NSMinX(group) + 0.08333 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.91667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.03750 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.96250 * NSHeight(group))];
        [bezier2Path lineToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.08333 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.08333 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.03750 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.03750 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.08333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.12917 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.03750 * NSHeight(group))];
        [bezier2Path lineToPoint: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.91667 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.08333 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.96250 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.12917 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezier2Path closePath];
        [bezier2Path setMiterLimit: 4];
        [bezier2Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier2Path fill];
    }
}

+ (void)drawShuffleButtonWithFrame: (NSRect)frame active: (BOOL)active;
{

    //// Gradient Declarations
    NSGradient* grayFakeGradient = [NSGradient.alloc initWithStartingColor: StreamCloudStyles.grayDark endingColor: StreamCloudStyles.grayDark];

    //// Variable Declarations
    NSGradient* fillGradient = active ? StreamCloudStyles.orangeGradient : grayFakeGradient;


    //// Subframes
    NSRect group5 = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame) + 0.2, NSHeight(frame));


    //// Group 5
    {
        //// Bezier 10 Drawing
        NSBezierPath* bezier10Path = NSBezierPath.bezierPath;
        [bezier10Path moveToPoint: NSMakePoint(NSMinX(group5) + 0.06211 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.16149 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.31677 * NSWidth(group5), NSMinY(group5) + 0.53929 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.40373 * NSWidth(group5), NSMinY(group5) + 0.63929 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.23292 * NSWidth(group5), NSMinY(group5) + 0.83571 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.19876 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.22360 * NSWidth(group5), NSMinY(group5) + 0.84643 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.21118 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.19565 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.19876 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.19876 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.18634 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.19255 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.18944 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.06211 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.00000 * NSWidth(group5), NSMinY(group5) + 0.78571 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.02795 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.00000 * NSWidth(group5), NSMinY(group5) + 0.82500 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.06211 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.00000 * NSWidth(group5), NSMinY(group5) + 0.75000 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.02795 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5))];
        [bezier10Path closePath];
        [bezier10Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier10Path angle: 90];


        //// Bezier 11 Drawing
        NSBezierPath* bezier11Path = NSBezierPath.bezierPath;
        [bezier11Path moveToPoint: NSMakePoint(NSMinX(group5) + 0.70807 * NSWidth(group5), NSMinY(group5) + 0.71429 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.71429 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.57143 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.99689 * NSWidth(group5), NSMinY(group5) + 0.78571 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 1.00000 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.68634 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.68634 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.64286 * NSWidth(group5), NSMinY(group5) + 0.83571 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.67081 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.65528 * NSWidth(group5), NSMinY(group5) + 0.85000 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.16460 * NSWidth(group5), NSMinY(group5) + 0.28571 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.06522 * NSWidth(group5), NSMinY(group5) + 0.28571 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.00311 * NSWidth(group5), NSMinY(group5) + 0.21429 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.03106 * NSWidth(group5), NSMinY(group5) + 0.28571 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.00311 * NSWidth(group5), NSMinY(group5) + 0.25357 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.06522 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.00311 * NSWidth(group5), NSMinY(group5) + 0.17500 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.03106 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.18944 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.23913 * NSWidth(group5), NSMinY(group5) + 0.17500 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.21118 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.22981 * NSWidth(group5), NSMinY(group5) + 0.15357 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.70807 * NSWidth(group5), NSMinY(group5) + 0.71429 * NSHeight(group5))];
        [bezier11Path closePath];
        [bezier11Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier11Path angle: 90];


        //// Bezier 12 Drawing
        NSBezierPath* bezier12Path = NSBezierPath.bezierPath;
        [bezier12Path moveToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.71739 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.56211 * NSWidth(group5), NSMinY(group5) + 0.46071 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.47516 * NSWidth(group5), NSMinY(group5) + 0.36071 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.63665 * NSWidth(group5), NSMinY(group5) + 0.17500 * NSHeight(group5))];
        [bezier12Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.68944 * NSWidth(group5), NSMinY(group5) + 0.13929 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.64596 * NSWidth(group5), NSMinY(group5) + 0.15357 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.66770 * NSWidth(group5), NSMinY(group5) + 0.13929 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.13929 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.00000 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 1.00000 * NSWidth(group5), NSMinY(group5) + 0.21429 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.42857 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path closePath];
        [bezier12Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier12Path angle: 90];
    }
}

+ (void)drawRepeatButtonWithFrame: (NSRect)frame active: (BOOL)active;
{

    //// Gradient Declarations
    NSGradient* grayFakeGradient = [NSGradient.alloc initWithStartingColor: StreamCloudStyles.grayDark endingColor: StreamCloudStyles.grayDark];

    //// Variable Declarations
    NSGradient* fillGradient = active ? StreamCloudStyles.orangeGradient : grayFakeGradient;


    //// Subframes
    NSRect group6 = NSMakeRect(NSMinX(frame), NSMinY(frame) + 0.1, NSWidth(frame) + 0.1, NSHeight(frame) - 0.1);


    //// Group 6
    {
        //// Bezier 13 Drawing
        NSBezierPath* bezier13Path = NSBezierPath.bezierPath;
        [bezier13Path moveToPoint: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.49833 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.34268 * NSWidth(group6), NSMinY(group6) + 0.73244 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.62876 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.22118 * NSWidth(group6), NSMinY(group6) + 0.73244 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 0.73244 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 0.59866 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.90343 * NSWidth(group6), NSMinY(group6) + 0.79933 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 1.00000 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 0.86622 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.34268 * NSWidth(group6), NSMinY(group6) + 0.86622 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.00000 * NSWidth(group6), NSMinY(group6) + 0.49833 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.15265 * NSWidth(group6), NSMinY(group6) + 0.86622 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.00000 * NSWidth(group6), NSMinY(group6) + 0.70234 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.02492 * NSWidth(group6), NSMinY(group6) + 0.35786 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.00000 * NSWidth(group6), NSMinY(group6) + 0.44816 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.00935 * NSWidth(group6), NSMinY(group6) + 0.40134 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.46488 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.49833 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.47826 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.48829 * NSHeight(group6))];
        [bezier13Path closePath];
        [bezier13Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier13Path angle: -90];


        //// Bezier 14 Drawing
        NSBezierPath* bezier14Path = NSBezierPath.bezierPath;
        [bezier14Path moveToPoint: NSMakePoint(NSMinX(group6) + 0.97196 * NSWidth(group6), NSMinY(group6) + 0.63880 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.87227 * NSWidth(group6), NSMinY(group6) + 0.53177 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.87539 * NSWidth(group6), NSMinY(group6) + 0.50167 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.87227 * NSWidth(group6), NSMinY(group6) + 0.52174 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.87539 * NSWidth(group6), NSMinY(group6) + 0.51171 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.65732 * NSWidth(group6), NSMinY(group6) + 0.26756 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.87539 * NSWidth(group6), NSMinY(group6) + 0.37124 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.77882 * NSWidth(group6), NSMinY(group6) + 0.26756 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 0.26756 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 0.40134 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.09657 * NSWidth(group6), NSMinY(group6) + 0.20067 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 0.00000 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 0.13378 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.65732 * NSWidth(group6), NSMinY(group6) + 0.13378 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 1.00000 * NSWidth(group6), NSMinY(group6) + 0.50167 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.84735 * NSWidth(group6), NSMinY(group6) + 0.13378 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 1.00000 * NSWidth(group6), NSMinY(group6) + 0.29766 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.97196 * NSWidth(group6), NSMinY(group6) + 0.63880 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.99688 * NSWidth(group6), NSMinY(group6) + 0.54849 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.98754 * NSWidth(group6), NSMinY(group6) + 0.59532 * NSHeight(group6))];
        [bezier14Path closePath];
        [bezier14Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier14Path angle: -90];
    }
}

+ (void)drawSoundCloudLogoWithFrame: (NSRect)frame;
{


    //// Subframes
    NSRect group = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame));


    //// Group
    {
        //// Bezier 15 Drawing
        NSBezierPath* bezier15Path = NSBezierPath.bezierPath;
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.10556 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.05237 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.43333 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.02494 * NSWidth(group), NSMinY(group) + 0.44444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.43889 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.02993 * NSWidth(group), NSMinY(group) + 0.44444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.43333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.01995 * NSWidth(group), NSMinY(group) + 0.44444 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.43889 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.10556 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.02494 * NSWidth(group), NSMinY(group) + 0.09444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.10000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.01995 * NSWidth(group), NSMinY(group) + 0.09444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.10556 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.02993 * NSWidth(group), NSMinY(group) + 0.10000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.10000 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.15212 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.63889 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.12469 * NSWidth(group), NSMinY(group) + 0.65556 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.65000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.13217 * NSWidth(group), NSMinY(group) + 0.65556 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.63889 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.11721 * NSWidth(group), NSMinY(group) + 0.65556 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.65000 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.09975 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.12469 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.00556 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.11721 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.13217 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.02222 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.25187 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.77222 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.22444 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.78333 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.23192 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.77222 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.21696 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.78333 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.19950 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.02222 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.22444 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.21696 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.02222 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.23192 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.35162 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.77778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.32668 * NSWidth(group), NSMinY(group) + 0.80556 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.33416 * NSWidth(group), NSMinY(group) + 0.80556 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.77778 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.31671 * NSWidth(group), NSMinY(group) + 0.80556 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.30424 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.32668 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.31920 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.33416 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.44888 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.84444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.42394 * NSWidth(group), NSMinY(group) + 0.87222 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.86111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.43392 * NSWidth(group), NSMinY(group) + 0.87222 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.84444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.41397 * NSWidth(group), NSMinY(group) + 0.87222 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.86111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.39900 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.42394 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.41397 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.43392 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.51372 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.87032 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.51372 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.86783 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.28333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.94015 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.12778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.87032 * NSWidth(group), NSMinY(group) + 0.56667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.43889 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.94264 * NSWidth(group), NSMinY(group) + 0.56667 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.82045 * NSWidth(group), NSMinY(group) + 0.54444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.85287 * NSWidth(group), NSMinY(group) + 0.56667 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.83541 * NSWidth(group), NSMinY(group) + 0.56111 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.59352 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.81047 * NSWidth(group), NSMinY(group) + 0.80000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.71322 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.51122 * NSWidth(group), NSMinY(group) + 0.96667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.56359 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.53616 * NSWidth(group), NSMinY(group) + 0.98889 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.93333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.50125 * NSWidth(group), NSMinY(group) + 0.96111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.95000 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.03333 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.51372 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.50623 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path setMiterLimit: 4];
        [StreamCloudStyles.grayDark setFill];
        [bezier15Path fill];
    }
}

+ (void)drawPlayingIndicatorWithFrame: (NSRect)frame;
{

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame))];
    [StreamCloudStyles.orangeGradient drawInBezierPath: rectanglePath angle: 90];
}

+ (void)drawSeperatorViewWithFrame: (NSRect)frame;
{
    //// Color Declarations
    NSColor* seperatorColor = [NSColor colorWithCalibratedRed: 0.773 green: 0.773 blue: 0.773 alpha: 1];

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame))];
    [seperatorColor setFill];
    [rectanglePath fill];
}

#pragma mark Generated Images

+ (NSImage*)imageOfPlayPauseButtonWithFrame: (NSRect)frame playing: (BOOL)playing;
{
    NSImage* imageOfPlayPauseButton = [NSImage.alloc initWithSize: NSMakeSize(48, 48)];
    [imageOfPlayPauseButton lockFocus];
    [StreamCloudStyles drawPlayPauseButtonWithFrame: frame playing: playing];
    [imageOfPlayPauseButton unlockFocus];

    return imageOfPlayPauseButton;
}

+ (NSImage*)imageOfShuffleButtonWithFrame: (NSRect)frame active: (BOOL)active;
{
    NSImage* imageOfShuffleButton = [NSImage.alloc initWithSize: NSMakeSize(32, 28)];
    [imageOfShuffleButton lockFocus];
    [StreamCloudStyles drawShuffleButtonWithFrame: frame active: active];
    [imageOfShuffleButton unlockFocus];

    return imageOfShuffleButton;
}

+ (NSImage*)imageOfRepeatButtonWithFrame: (NSRect)frame active: (BOOL)active;
{
    NSImage* imageOfRepeatButton = [NSImage.alloc initWithSize: NSMakeSize(32, 30)];
    [imageOfRepeatButton lockFocus];
    [StreamCloudStyles drawRepeatButtonWithFrame: frame active: active];
    [imageOfRepeatButton unlockFocus];

    return imageOfRepeatButton;
}

+ (NSImage*)imageOfSoundCloudLogoWithFrame: (NSRect)frame;
{
    NSImage* imageOfSoundCloudLogo = [NSImage.alloc initWithSize: NSMakeSize(40, 18)];
    [imageOfSoundCloudLogo lockFocus];
    [StreamCloudStyles drawSoundCloudLogoWithFrame: frame];
    [imageOfSoundCloudLogo unlockFocus];

    return imageOfSoundCloudLogo;
}

+ (NSImage*)imageOfPlayingIndicatorWithFrame: (NSRect)frame;
{
    NSImage* imageOfPlayingIndicator = [NSImage.alloc initWithSize: NSMakeSize(240, 120)];
    [imageOfPlayingIndicator lockFocus];
    [StreamCloudStyles drawPlayingIndicatorWithFrame: frame];
    [imageOfPlayingIndicator unlockFocus];

    return imageOfPlayingIndicator;
}

@end
