//
//  StreamCloudStyles.m
//  StreamCloud
//
//  Created by Peter Amende on 25.06.14.
//  Copyright (c) 2014 Call a Nerd. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "StreamCloudStyles.h"


@implementation StreamCloudStyles

#pragma mark Cache

static NSColor* _orangeLight = nil;
static NSColor* _orangeMedium = nil;
static NSColor* _orangeDark = nil;
static NSColor* _grayMedium = nil;
static NSColor* _grayDark = nil;
static NSColor* _grayLight = nil;
static NSColor* _seperatorColor = nil;
static NSColor* _artistLabelColor = nil;
static NSColor* _durationLabelColor = nil;

static NSGradient* _orangeGradient = nil;

static NSImage* _imageOfMenuBarIcon = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _orangeLight = [NSColor colorWithCalibratedRed: 1 green: 0.545 blue: 0 alpha: 1];
    _orangeMedium = [NSColor colorWithCalibratedRed: 1 green: 0.416 blue: 0 alpha: 1];
    _orangeDark = [NSColor colorWithCalibratedRed: 1 green: 0.282 blue: 0 alpha: 1];
    _artistLabelColor = _orangeDark;
    _grayMedium = [NSColor colorWithCalibratedRed: 0.298 green: 0.318 blue: 0.329 alpha: 1];
    _durationLabelColor = _grayMedium;
    _grayDark = [NSColor colorWithCalibratedRed: 0.2 green: 0.2 blue: 0.2 alpha: 1];
    _grayLight = [NSColor colorWithCalibratedRed: 0.91 green: 0.91 blue: 0.91 alpha: 1];
    _seperatorColor = [NSColor colorWithCalibratedRed: 0.773 green: 0.773 blue: 0.773 alpha: 1];

    // Gradients Initialization
    _orangeGradient = [NSGradient.alloc initWithStartingColor: StreamCloudStyles.orangeDark endingColor: StreamCloudStyles.orangeLight];

}

#pragma mark Colors

+ (NSColor*)orangeLight { return _orangeLight; }
+ (NSColor*)orangeMedium { return _orangeMedium; }
+ (NSColor*)orangeDark { return _orangeDark; }
+ (NSColor*)grayMedium { return _grayMedium; }
+ (NSColor*)grayDark { return _grayDark; }
+ (NSColor*)grayLight { return _grayLight; }
+ (NSColor*)seperatorColor { return _seperatorColor; }
+ (NSColor*)artistLabelColor { return _artistLabelColor; }
+ (NSColor*)durationLabelColor { return _durationLabelColor; }

#pragma mark Gradients

+ (NSGradient*)orangeGradient { return _orangeGradient; }

#pragma mark Drawing Methods

+ (void)drawPlayPauseButtonWithFrame: (NSRect)frame playing: (BOOL)playing;
{
    //// Color Declarations
    NSColor* fakeClearColor = [NSColor colorWithCalibratedRed: 1 green: 1 blue: 1 alpha: 0];

    //// Variable Declarations
    NSColor* playFillColor = playing ? fakeClearColor : StreamCloudStyles.grayDark;
    NSColor* pauseFillColor = playing ? StreamCloudStyles.grayDark : fakeClearColor;


    //// Subframes
    NSRect group4 = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame));


    //// Group 4
    {
        //// Bezier 8 Drawing
        NSBezierPath* bezier8Path = NSBezierPath.bezierPath;
        [bezier8Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.00000 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.22292 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.00000 * NSWidth(group4), NSMinY(group4) + 0.77708 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.00000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.00000 * NSWidth(group4), NSMinY(group4) + 0.22292 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.22292 * NSWidth(group4), NSMinY(group4) + 0.00000 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 1.00000 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.77708 * NSWidth(group4), NSMinY(group4) + 0.00000 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 1.00000 * NSWidth(group4), NSMinY(group4) + 0.22292 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 1.00000 * NSWidth(group4), NSMinY(group4) + 0.77708 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.77708 * NSWidth(group4), NSMinY(group4) + 1.00000 * NSHeight(group4))];
        [bezier8Path closePath];
        [bezier8Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.04167 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.24583 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.04167 * NSWidth(group4), NSMinY(group4) + 0.24583 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.95833 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.04167 * NSWidth(group4), NSMinY(group4) + 0.75417 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.24583 * NSWidth(group4), NSMinY(group4) + 0.95833 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.95833 * NSWidth(group4), NSMinY(group4) + 0.50000 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.75417 * NSWidth(group4), NSMinY(group4) + 0.95833 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.95833 * NSWidth(group4), NSMinY(group4) + 0.75417 * NSHeight(group4))];
        [bezier8Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.50000 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.95833 * NSWidth(group4), NSMinY(group4) + 0.24583 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.75417 * NSWidth(group4), NSMinY(group4) + 0.04167 * NSHeight(group4))];
        [bezier8Path closePath];
        [bezier8Path setMiterLimit: 4];
        [bezier8Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier8Path fill];


        //// Bezier 9 Drawing
        NSBezierPath* bezier9Path = NSBezierPath.bezierPath;
        [bezier9Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.75625 * NSWidth(group4), NSMinY(group4) + 0.52500 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.39375 * NSWidth(group4), NSMinY(group4) + 0.74583 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.72917 * NSWidth(group4), NSMinY(group4) + 0.54167 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.41042 * NSWidth(group4), NSMinY(group4) + 0.73542 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.72292 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.37292 * NSWidth(group4), NSMinY(group4) + 0.75833 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.74167 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.27917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.70625 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.30208 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.39375 * NSWidth(group4), NSMinY(group4) + 0.25625 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.35417 * NSWidth(group4), NSMinY(group4) + 0.25625 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.37708 * NSWidth(group4), NSMinY(group4) + 0.24583 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.75833 * NSWidth(group4), NSMinY(group4) + 0.47917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.41667 * NSWidth(group4), NSMinY(group4) + 0.27083 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.73750 * NSWidth(group4), NSMinY(group4) + 0.46667 * NSHeight(group4))];
        [bezier9Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.75625 * NSWidth(group4), NSMinY(group4) + 0.52500 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.77500 * NSWidth(group4), NSMinY(group4) + 0.48750 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.77500 * NSWidth(group4), NSMinY(group4) + 0.51250 * NSHeight(group4))];
        [bezier9Path closePath];
        [bezier9Path setMiterLimit: 4];
        [bezier9Path setWindingRule: NSEvenOddWindingRule];
        [playFillColor setFill];
        [bezier9Path fill];


        //// Bezier 6 Drawing
        NSBezierPath* bezier6Path = NSBezierPath.bezierPath;
        [bezier6Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.39792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.35208 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.32917 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.35208 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.31250 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.33125 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.39792 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.42083 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4))];
        [bezier6Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4))];
        [bezier6Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.39792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.43750 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.41875 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier6Path closePath];
        [bezier6Path setMiterLimit: 4];
        [bezier6Path setWindingRule: NSEvenOddWindingRule];
        [pauseFillColor setFill];
        [bezier6Path fill];


        //// Bezier 7 Drawing
        NSBezierPath* bezier7Path = NSBezierPath.bezierPath;
        [bezier7Path moveToPoint: NSMakePoint(NSMinX(group4) + 0.64792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.60208 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.57917 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.60208 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.56250 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.58125 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.64792 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.31042 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.67083 * NSWidth(group4), NSMinY(group4) + 0.26875 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.28750 * NSHeight(group4))];
        [bezier7Path lineToPoint: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.68750 * NSHeight(group4))];
        [bezier7Path curveToPoint: NSMakePoint(NSMinX(group4) + 0.64792 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4)) controlPoint1: NSMakePoint(NSMinX(group4) + 0.68750 * NSWidth(group4), NSMinY(group4) + 0.71042 * NSHeight(group4)) controlPoint2: NSMakePoint(NSMinX(group4) + 0.66875 * NSWidth(group4), NSMinY(group4) + 0.72917 * NSHeight(group4))];
        [bezier7Path closePath];
        [bezier7Path setMiterLimit: 4];
        [bezier7Path setWindingRule: NSEvenOddWindingRule];
        [pauseFillColor setFill];
        [bezier7Path fill];
    }
}

+ (void)drawNextButtonWithFrame: (NSRect)frame;
{


    //// Subframes
    NSRect group2 = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame) + 0.1, NSHeight(frame));


    //// Group 2
    {
        //// Bezier 3 Drawing
        NSBezierPath* bezier3Path = NSBezierPath.bezierPath;
        [bezier3Path moveToPoint: NSMakePoint(NSMinX(group2) + 0.80083 * NSWidth(group2), NSMinY(group2) + 0.54583 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.07884 * NSWidth(group2), NSMinY(group2) + 0.98750 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.74689 * NSWidth(group2), NSMinY(group2) + 0.57917 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.11203 * NSWidth(group2), NSMinY(group2) + 0.96667 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.94167 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.03734 * NSWidth(group2), NSMinY(group2) + 1.01250 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.97917 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.05833 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.90833 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.10417 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.07884 * NSWidth(group2), NSMinY(group2) + 0.01250 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.00000 * NSWidth(group2), NSMinY(group2) + 0.01250 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.04564 * NSWidth(group2), NSMinY(group2) + -0.00833 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.80083 * NSWidth(group2), NSMinY(group2) + 0.45417 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.12448 * NSWidth(group2), NSMinY(group2) + 0.04167 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.76349 * NSWidth(group2), NSMinY(group2) + 0.42917 * NSHeight(group2))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.80083 * NSWidth(group2), NSMinY(group2) + 0.54583 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.83817 * NSWidth(group2), NSMinY(group2) + 0.47083 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.83817 * NSWidth(group2), NSMinY(group2) + 0.52500 * NSHeight(group2))];
        [bezier3Path closePath];
        [bezier3Path setMiterLimit: 4];
        [bezier3Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier3Path fill];


        //// Bezier 4 Drawing
        NSBezierPath* bezier4Path = NSBezierPath.bezierPath;
        [bezier4Path moveToPoint: NSMakePoint(NSMinX(group2) + 0.91701 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.91667 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.87137 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.96250 * NSHeight(group2))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.08333 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.91701 * NSWidth(group2), NSMinY(group2) + 0.00000 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.83402 * NSWidth(group2), NSMinY(group2) + 0.03750 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.87137 * NSWidth(group2), NSMinY(group2) + 0.00000 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.08333 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 0.96266 * NSWidth(group2), NSMinY(group2) + 0.00000 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.03750 * NSHeight(group2))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.91667 * NSHeight(group2))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group2) + 0.91701 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2)) controlPoint1: NSMakePoint(NSMinX(group2) + 1.00000 * NSWidth(group2), NSMinY(group2) + 0.96250 * NSHeight(group2)) controlPoint2: NSMakePoint(NSMinX(group2) + 0.96266 * NSWidth(group2), NSMinY(group2) + 1.00000 * NSHeight(group2))];
        [bezier4Path closePath];
        [bezier4Path setMiterLimit: 4];
        [bezier4Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier4Path fill];
    }
}

+ (void)drawPreviousButtonWithFrame: (NSRect)frame;
{


    //// Subframes
    NSRect group = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame));


    //// Group
    {
        //// Bezier Drawing
        NSBezierPath* bezierPath = NSBezierPath.bezierPath;
        [bezierPath moveToPoint: NSMakePoint(NSMinX(group) + 0.92083 * NSWidth(group), NSMinY(group) + 0.99167 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.19583 * NSWidth(group), NSMinY(group) + 0.55000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.87500 * NSWidth(group), NSMinY(group) + 0.96250 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.23333 * NSWidth(group), NSMinY(group) + 0.57500 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.19583 * NSWidth(group), NSMinY(group) + 0.45417 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.16250 * NSWidth(group), NSMinY(group) + 0.52917 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.15833 * NSWidth(group), NSMinY(group) + 0.47500 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.92083 * NSWidth(group), NSMinY(group) + 0.01250 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.25000 * NSWidth(group), NSMinY(group) + 0.42083 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.88750 * NSWidth(group), NSMinY(group) + 0.03333 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.05833 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.96250 * NSWidth(group), NSMinY(group) + -0.01250 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.02083 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.94167 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.09167 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.89583 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.92083 * NSWidth(group), NSMinY(group) + 0.99167 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.98750 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.95417 * NSWidth(group), NSMinY(group) + 1.01250 * NSHeight(group))];
        [bezierPath closePath];
        [bezierPath setMiterLimit: 4];
        [bezierPath setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        NSBezierPath* bezier2Path = NSBezierPath.bezierPath;
        [bezier2Path moveToPoint: NSMakePoint(NSMinX(group) + 0.08333 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.91667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.03750 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.96250 * NSHeight(group))];
        [bezier2Path lineToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.08333 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.08333 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.03750 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.03750 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.08333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.12917 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.03750 * NSHeight(group))];
        [bezier2Path lineToPoint: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.91667 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.08333 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.16667 * NSWidth(group), NSMinY(group) + 0.96250 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.12917 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezier2Path closePath];
        [bezier2Path setMiterLimit: 4];
        [bezier2Path setWindingRule: NSEvenOddWindingRule];
        [StreamCloudStyles.grayDark setFill];
        [bezier2Path fill];
    }
}

+ (void)drawShuffleButtonWithFrame: (NSRect)frame active: (BOOL)active;
{

    //// Gradient Declarations
    NSGradient* grayFakeGradient = [NSGradient.alloc initWithStartingColor: StreamCloudStyles.grayDark endingColor: StreamCloudStyles.grayDark];

    //// Variable Declarations
    NSGradient* fillGradient = active ? StreamCloudStyles.orangeGradient : grayFakeGradient;


    //// Subframes
    NSRect group5 = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame) + 0.2, NSHeight(frame));


    //// Group 5
    {
        //// Bezier 10 Drawing
        NSBezierPath* bezier10Path = NSBezierPath.bezierPath;
        [bezier10Path moveToPoint: NSMakePoint(NSMinX(group5) + 0.06211 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.16149 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.31677 * NSWidth(group5), NSMinY(group5) + 0.53929 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.40373 * NSWidth(group5), NSMinY(group5) + 0.63929 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.23292 * NSWidth(group5), NSMinY(group5) + 0.83571 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.19876 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.22360 * NSWidth(group5), NSMinY(group5) + 0.84643 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.21118 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.19565 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.19876 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.19876 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.18634 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.19255 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.18944 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.06211 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.00000 * NSWidth(group5), NSMinY(group5) + 0.78571 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.02795 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.00000 * NSWidth(group5), NSMinY(group5) + 0.82500 * NSHeight(group5))];
        [bezier10Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.06211 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.00000 * NSWidth(group5), NSMinY(group5) + 0.75000 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.02795 * NSWidth(group5), NSMinY(group5) + 0.71786 * NSHeight(group5))];
        [bezier10Path closePath];
        [bezier10Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier10Path angle: 90];


        //// Bezier 11 Drawing
        NSBezierPath* bezier11Path = NSBezierPath.bezierPath;
        [bezier11Path moveToPoint: NSMakePoint(NSMinX(group5) + 0.70807 * NSWidth(group5), NSMinY(group5) + 0.71429 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.71429 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.57143 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.99689 * NSWidth(group5), NSMinY(group5) + 0.78571 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 1.00000 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.68634 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.68634 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.64286 * NSWidth(group5), NSMinY(group5) + 0.83571 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.67081 * NSWidth(group5), NSMinY(group5) + 0.85714 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.65528 * NSWidth(group5), NSMinY(group5) + 0.85000 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.16460 * NSWidth(group5), NSMinY(group5) + 0.28571 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.06522 * NSWidth(group5), NSMinY(group5) + 0.28571 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.00311 * NSWidth(group5), NSMinY(group5) + 0.21429 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.03106 * NSWidth(group5), NSMinY(group5) + 0.28571 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.00311 * NSWidth(group5), NSMinY(group5) + 0.25357 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.06522 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.00311 * NSWidth(group5), NSMinY(group5) + 0.17500 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.03106 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.18944 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5))];
        [bezier11Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.23913 * NSWidth(group5), NSMinY(group5) + 0.17500 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.21118 * NSWidth(group5), NSMinY(group5) + 0.14286 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.22981 * NSWidth(group5), NSMinY(group5) + 0.15357 * NSHeight(group5))];
        [bezier11Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.70807 * NSWidth(group5), NSMinY(group5) + 0.71429 * NSHeight(group5))];
        [bezier11Path closePath];
        [bezier11Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier11Path angle: 90];


        //// Bezier 12 Drawing
        NSBezierPath* bezier12Path = NSBezierPath.bezierPath;
        [bezier12Path moveToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.71739 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.56211 * NSWidth(group5), NSMinY(group5) + 0.46071 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.47516 * NSWidth(group5), NSMinY(group5) + 0.36071 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.63665 * NSWidth(group5), NSMinY(group5) + 0.17500 * NSHeight(group5))];
        [bezier12Path curveToPoint: NSMakePoint(NSMinX(group5) + 0.68944 * NSWidth(group5), NSMinY(group5) + 0.13929 * NSHeight(group5)) controlPoint1: NSMakePoint(NSMinX(group5) + 0.64596 * NSWidth(group5), NSMinY(group5) + 0.15357 * NSHeight(group5)) controlPoint2: NSMakePoint(NSMinX(group5) + 0.66770 * NSWidth(group5), NSMinY(group5) + 0.13929 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.13929 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.00000 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 1.00000 * NSWidth(group5), NSMinY(group5) + 0.21429 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.42857 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.78261 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path lineToPoint: NSMakePoint(NSMinX(group5) + 0.77950 * NSWidth(group5), NSMinY(group5) + 0.28214 * NSHeight(group5))];
        [bezier12Path closePath];
        [bezier12Path setMiterLimit: 4];
        [fillGradient drawInBezierPath: bezier12Path angle: 90];
    }
}

+ (void)drawRepeatButtonWithFrame: (NSRect)frame repeatMode: (CGFloat)repeatMode;
{

    //// Gradient Declarations
    NSGradient* grayFakeGradient = [NSGradient.alloc initWithStartingColor: StreamCloudStyles.grayDark endingColor: StreamCloudStyles.grayDark];
    NSGradient* translucentFakeGradient = [NSGradient.alloc initWithStartingColor: NSColor.clearColor endingColor: NSColor.clearColor];

    //// Variable Declarations
    NSGradient* colorForSingleRepeatSymbol = repeatMode == 2 ? StreamCloudStyles.orangeGradient : grayFakeGradient;
    NSGradient* colorForTrackRepeatSymbol = repeatMode == 3 ? StreamCloudStyles.orangeGradient : translucentFakeGradient;
    NSGradient* colorToUseForSingleRepeatSymbol = repeatMode < 3 ? colorForSingleRepeatSymbol : translucentFakeGradient;


    //// Subframes
    NSRect group6 = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame) + 0.1, NSHeight(frame) - 0.1);
    NSRect group = NSMakeRect(NSMinX(frame), NSMinY(frame) + 1, NSWidth(frame), NSHeight(frame) - 1);


    //// Group 6
    {
        //// Bezier 13 Drawing
        NSBezierPath* bezier13Path = NSBezierPath.bezierPath;
        [bezier13Path moveToPoint: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.50167 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.34268 * NSWidth(group6), NSMinY(group6) + 0.26756 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.37124 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.22118 * NSWidth(group6), NSMinY(group6) + 0.26756 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 0.26756 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 0.40134 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.90343 * NSWidth(group6), NSMinY(group6) + 0.20067 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 0.00000 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.62305 * NSWidth(group6), NSMinY(group6) + 0.13378 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.34268 * NSWidth(group6), NSMinY(group6) + 0.13378 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.00000 * NSWidth(group6), NSMinY(group6) + 0.50167 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.15265 * NSWidth(group6), NSMinY(group6) + 0.13378 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.00000 * NSWidth(group6), NSMinY(group6) + 0.29766 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.02492 * NSWidth(group6), NSMinY(group6) + 0.64214 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.00000 * NSWidth(group6), NSMinY(group6) + 0.55184 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.00935 * NSWidth(group6), NSMinY(group6) + 0.59866 * NSHeight(group6))];
        [bezier13Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.53512 * NSHeight(group6))];
        [bezier13Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.50167 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.52174 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.12461 * NSWidth(group6), NSMinY(group6) + 0.51171 * NSHeight(group6))];
        [bezier13Path closePath];
        [bezier13Path setMiterLimit: 4];
        [colorToUseForSingleRepeatSymbol drawInBezierPath: bezier13Path angle: 90];


        //// Bezier 14 Drawing
        NSBezierPath* bezier14Path = NSBezierPath.bezierPath;
        [bezier14Path moveToPoint: NSMakePoint(NSMinX(group6) + 0.97196 * NSWidth(group6), NSMinY(group6) + 0.36120 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.87227 * NSWidth(group6), NSMinY(group6) + 0.46823 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.87539 * NSWidth(group6), NSMinY(group6) + 0.49833 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.87227 * NSWidth(group6), NSMinY(group6) + 0.47826 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.87539 * NSWidth(group6), NSMinY(group6) + 0.48829 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.65732 * NSWidth(group6), NSMinY(group6) + 0.73244 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.87539 * NSWidth(group6), NSMinY(group6) + 0.62876 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.77882 * NSWidth(group6), NSMinY(group6) + 0.73244 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 0.73244 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 0.59866 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.09657 * NSWidth(group6), NSMinY(group6) + 0.79933 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 1.00000 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.37695 * NSWidth(group6), NSMinY(group6) + 0.86622 * NSHeight(group6))];
        [bezier14Path lineToPoint: NSMakePoint(NSMinX(group6) + 0.65732 * NSWidth(group6), NSMinY(group6) + 0.86622 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 1.00000 * NSWidth(group6), NSMinY(group6) + 0.49833 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.84735 * NSWidth(group6), NSMinY(group6) + 0.86622 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 1.00000 * NSWidth(group6), NSMinY(group6) + 0.70234 * NSHeight(group6))];
        [bezier14Path curveToPoint: NSMakePoint(NSMinX(group6) + 0.97196 * NSWidth(group6), NSMinY(group6) + 0.36120 * NSHeight(group6)) controlPoint1: NSMakePoint(NSMinX(group6) + 0.99688 * NSWidth(group6), NSMinY(group6) + 0.45151 * NSHeight(group6)) controlPoint2: NSMakePoint(NSMinX(group6) + 0.98754 * NSWidth(group6), NSMinY(group6) + 0.40468 * NSHeight(group6))];
        [bezier14Path closePath];
        [bezier14Path setMiterLimit: 4];
        [colorToUseForSingleRepeatSymbol drawInBezierPath: bezier14Path angle: 90];
    }


    //// Group
    {
        //// Bezier Drawing
        NSBezierPath* bezierPath = NSBezierPath.bezierPath;
        [bezierPath moveToPoint: NSMakePoint(NSMinX(group) + 0.78056 * NSWidth(group), NSMinY(group) + 0.54023 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.56113 * NSWidth(group), NSMinY(group) + 0.27203 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.65831 * NSWidth(group), NSMinY(group) + 0.54023 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.56113 * NSWidth(group), NSMinY(group) + 0.42146 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.78056 * NSWidth(group), NSMinY(group) + 0.00383 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.56113 * NSWidth(group), NSMinY(group) + 0.12261 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.65831 * NSWidth(group), NSMinY(group) + 0.00383 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.27203 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.90282 * NSWidth(group), NSMinY(group) + 0.00383 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.12261 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.78056 * NSWidth(group), NSMinY(group) + 0.54023 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.42146 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.90282 * NSWidth(group), NSMinY(group) + 0.54023 * NSHeight(group))];
        [bezierPath closePath];
        [bezierPath moveToPoint: NSMakePoint(NSMinX(group) + 0.81191 * NSWidth(group), NSMinY(group) + 0.11877 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.78056 * NSWidth(group), NSMinY(group) + 0.11877 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.75862 * NSWidth(group), NSMinY(group) + 0.15709 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.78056 * NSWidth(group), NSMinY(group) + 0.12644 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.77429 * NSWidth(group), NSMinY(group) + 0.14559 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.71787 * NSWidth(group), NSMinY(group) + 0.16858 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.74922 * NSWidth(group), NSMinY(group) + 0.16475 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.72414 * NSWidth(group), NSMinY(group) + 0.16858 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.71787 * NSWidth(group), NSMinY(group) + 0.20690 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.77116 * NSWidth(group), NSMinY(group) + 0.20690 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.77116 * NSWidth(group), NSMinY(group) + 0.42529 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.81191 * NSWidth(group), NSMinY(group) + 0.42529 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.81191 * NSWidth(group), NSMinY(group) + 0.11877 * NSHeight(group))];
        [bezierPath closePath];
        [bezierPath moveToPoint: NSMakePoint(NSMinX(group) + 0.34169 * NSWidth(group), NSMinY(group) + 0.15326 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.12226 * NSWidth(group), NSMinY(group) + 0.42529 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.21944 * NSWidth(group), NSMinY(group) + 0.15326 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.12226 * NSWidth(group), NSMinY(group) + 0.27586 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.12539 * NSWidth(group), NSMinY(group) + 0.45977 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.12226 * NSWidth(group), NSMinY(group) + 0.43678 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.12226 * NSWidth(group), NSMinY(group) + 0.44828 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.02508 * NSWidth(group), NSMinY(group) + 0.58238 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.42146 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.00940 * NSWidth(group), NSMinY(group) + 0.53257 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.47893 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.34483 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.18774 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.15361 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.60502 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.51724 * NSWidth(group), NSMinY(group) + 0.15326 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.56426 * NSWidth(group), NSMinY(group) + 0.03831 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.53292 * NSWidth(group), NSMinY(group) + 0.09195 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.34169 * NSWidth(group), NSMinY(group) + 0.15326 * NSHeight(group))];
        [bezierPath closePath];
        [bezierPath moveToPoint: NSMakePoint(NSMinX(group) + 0.37304 * NSWidth(group), NSMinY(group) + 0.69349 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.65517 * NSWidth(group), NSMinY(group) + 0.69349 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.81191 * NSWidth(group), NSMinY(group) + 0.61303 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.71473 * NSWidth(group), NSMinY(group) + 0.69349 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.77116 * NSWidth(group), NSMinY(group) + 0.66284 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.99687 * NSWidth(group), NSMinY(group) + 0.49425 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.88401 * NSWidth(group), NSMinY(group) + 0.60536 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.94984 * NSWidth(group), NSMinY(group) + 0.55939 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.65831 * NSWidth(group), NSMinY(group) + 0.84674 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.96865 * NSWidth(group), NSMinY(group) + 0.69349 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.82759 * NSWidth(group), NSMinY(group) + 0.84674 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.37618 * NSWidth(group), NSMinY(group) + 0.84674 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.37618 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.09404 * NSWidth(group), NSMinY(group) + 0.77011 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.37618 * NSWidth(group), NSMinY(group) + 0.54023 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.37304 * NSWidth(group), NSMinY(group) + 0.69349 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.37304 * NSWidth(group), NSMinY(group) + 0.69349 * NSHeight(group))];
        [bezierPath closePath];
        [bezierPath setMiterLimit: 4];
        [colorForTrackRepeatSymbol drawInBezierPath: bezierPath angle: 90];
    }
}

+ (void)drawSoundCloudLogoWithFrame: (NSRect)frame;
{


    //// Subframes
    NSRect group = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame));


    //// Group
    {
        //// Bezier 15 Drawing
        NSBezierPath* bezier15Path = NSBezierPath.bezierPath;
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.10556 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.05237 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.43333 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.02494 * NSWidth(group), NSMinY(group) + 0.44444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.43889 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.02993 * NSWidth(group), NSMinY(group) + 0.44444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.43333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.01995 * NSWidth(group), NSMinY(group) + 0.44444 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.43889 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.10556 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.02494 * NSWidth(group), NSMinY(group) + 0.09444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.01496 * NSWidth(group), NSMinY(group) + 0.10000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.01995 * NSWidth(group), NSMinY(group) + 0.09444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.10556 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.02993 * NSWidth(group), NSMinY(group) + 0.10000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.03491 * NSWidth(group), NSMinY(group) + 0.10000 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.15212 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.63889 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.12469 * NSWidth(group), NSMinY(group) + 0.65556 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.65000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.13217 * NSWidth(group), NSMinY(group) + 0.65556 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.63889 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.11721 * NSWidth(group), NSMinY(group) + 0.65556 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.65000 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.09975 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.12469 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.11222 * NSWidth(group), NSMinY(group) + 0.00556 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.11721 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.13217 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.13716 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.02222 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.25187 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.77222 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.22444 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.78333 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.23192 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.77222 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.21696 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.78333 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.19950 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.02222 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.22444 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.20948 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.21696 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.02222 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.23192 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.23940 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.35162 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.77778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.32668 * NSWidth(group), NSMinY(group) + 0.80556 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.33416 * NSWidth(group), NSMinY(group) + 0.80556 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.77778 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.31671 * NSWidth(group), NSMinY(group) + 0.80556 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.79444 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.30424 * NSWidth(group), NSMinY(group) + 0.26667 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.32668 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.31172 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.31920 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.33416 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.34165 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.44888 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.84444 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.42394 * NSWidth(group), NSMinY(group) + 0.87222 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.86111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.43392 * NSWidth(group), NSMinY(group) + 0.87222 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.84444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.41397 * NSWidth(group), NSMinY(group) + 0.87222 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.86111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.39900 * NSWidth(group), NSMinY(group) + 0.26111 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.42394 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.40648 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.41397 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.02778 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.43392 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.44140 * NSWidth(group), NSMinY(group) + 0.01111 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(NSMinX(group) + 0.51372 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.87032 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.51372 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.86783 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.28333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.94015 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.12778 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.87032 * NSWidth(group), NSMinY(group) + 0.56667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.43889 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.94264 * NSWidth(group), NSMinY(group) + 0.56667 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.82045 * NSWidth(group), NSMinY(group) + 0.54444 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.85287 * NSWidth(group), NSMinY(group) + 0.56667 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.83541 * NSWidth(group), NSMinY(group) + 0.56111 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.59352 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.81047 * NSWidth(group), NSMinY(group) + 0.80000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.71322 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.51122 * NSWidth(group), NSMinY(group) + 0.96667 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.56359 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.53616 * NSWidth(group), NSMinY(group) + 0.98889 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.93333 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.50125 * NSWidth(group), NSMinY(group) + 0.96111 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.95000 * NSHeight(group))];
        [bezier15Path lineToPoint: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.03333 * NSHeight(group))];
        [bezier15Path curveToPoint: NSMakePoint(NSMinX(group) + 0.51372 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.49875 * NSWidth(group), NSMinY(group) + 0.01667 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.50623 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezier15Path closePath];
        [bezier15Path setMiterLimit: 4];
        [StreamCloudStyles.grayDark setFill];
        [bezier15Path fill];
    }
}

+ (void)drawPlayingIndicatorWithFrame: (NSRect)frame;
{

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame))];
    [StreamCloudStyles.orangeGradient drawInBezierPath: rectanglePath angle: 90];
}

+ (void)drawSeperatorViewWithFrame: (NSRect)frame;
{

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame))];
    [StreamCloudStyles.seperatorColor setFill];
    [rectanglePath fill];
}

+ (void)drawProgressIndicatorViewWithPercentShown: (CGFloat)percentShown;
{
    //// Color Declarations
    NSColor* progressIndicatorTrackColor = [NSColor colorWithCalibratedRed: 0 green: 0 blue: 0 alpha: 0.5];

    //// Variable Declarations
    CGFloat progressWidth = 320 * percentShown / 100.0;

    //// Track Drawing
    NSBezierPath* trackPath = [NSBezierPath bezierPathWithRect: NSMakeRect(0, 0, 320, 4)];
    [progressIndicatorTrackColor setFill];
    [trackPath fill];


    //// Progress Drawing
    CGFloat progressCornerRadius = 2;
    NSRect progressRect = NSMakeRect(0, 0, progressWidth, 4);
    NSRect progressInnerRect = NSInsetRect(progressRect, progressCornerRadius, progressCornerRadius);
    NSBezierPath* progressPath = NSBezierPath.bezierPath;
    [progressPath moveToPoint: NSMakePoint(NSMinX(progressRect), NSMinY(progressRect))];
    [progressPath appendBezierPathWithArcWithCenter: NSMakePoint(NSMaxX(progressInnerRect), NSMinY(progressInnerRect)) radius: progressCornerRadius startAngle: 270 endAngle: 360];
    [progressPath appendBezierPathWithArcWithCenter: NSMakePoint(NSMaxX(progressInnerRect), NSMaxY(progressInnerRect)) radius: progressCornerRadius startAngle: 0 endAngle: 90];
    [progressPath lineToPoint: NSMakePoint(NSMinX(progressRect), NSMaxY(progressRect))];
    [progressPath closePath];
    [StreamCloudStyles.orangeGradient drawInBezierPath: progressPath angle: 90];
}

+ (void)drawMenuBarIcon;
{

    //// Group
    {
        //// Bezier 15 Drawing
        NSBezierPath* bezier15Path = NSBezierPath.bezierPath;
        [bezier15Path moveToPoint: NSMakePoint(1.8, 5.66)];
        [bezier15Path lineToPoint: NSMakePoint(2.2, 7.43)];
        [bezier15Path lineToPoint: NSMakePoint(1.8, 9.27)];
        [bezier15Path curveToPoint: NSMakePoint(1.57, 9.39) controlPoint1: NSMakePoint(1.8, 9.33) controlPoint2: NSMakePoint(1.69, 9.39)];
        [bezier15Path curveToPoint: NSMakePoint(1.34, 9.27) controlPoint1: NSMakePoint(1.46, 9.39) controlPoint2: NSMakePoint(1.34, 9.33)];
        [bezier15Path lineToPoint: NSMakePoint(1, 7.43)];
        [bezier15Path lineToPoint: NSMakePoint(1.34, 5.66)];
        [bezier15Path curveToPoint: NSMakePoint(1.57, 5.54) controlPoint1: NSMakePoint(1.34, 5.6) controlPoint2: NSMakePoint(1.46, 5.54)];
        [bezier15Path curveToPoint: NSMakePoint(1.8, 5.66) controlPoint1: NSMakePoint(1.69, 5.6) controlPoint2: NSMakePoint(1.8, 5.6)];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(4.15, 4.68)];
        [bezier15Path lineToPoint: NSMakePoint(4.5, 7.37)];
        [bezier15Path lineToPoint: NSMakePoint(4.15, 11.53)];
        [bezier15Path curveToPoint: NSMakePoint(3.87, 11.71) controlPoint1: NSMakePoint(4.15, 11.65) controlPoint2: NSMakePoint(4.04, 11.71)];
        [bezier15Path curveToPoint: NSMakePoint(3.58, 11.53) controlPoint1: NSMakePoint(3.7, 11.71) controlPoint2: NSMakePoint(3.58, 11.65)];
        [bezier15Path lineToPoint: NSMakePoint(3.29, 7.37)];
        [bezier15Path lineToPoint: NSMakePoint(3.58, 4.68)];
        [bezier15Path curveToPoint: NSMakePoint(3.87, 4.5) controlPoint1: NSMakePoint(3.58, 4.56) controlPoint2: NSMakePoint(3.7, 4.5)];
        [bezier15Path curveToPoint: NSMakePoint(4.15, 4.68) controlPoint1: NSMakePoint(4.04, 4.5) controlPoint2: NSMakePoint(4.15, 4.62)];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(6.51, 4.74)];
        [bezier15Path lineToPoint: NSMakePoint(6.79, 7.43)];
        [bezier15Path lineToPoint: NSMakePoint(6.51, 12.99)];
        [bezier15Path curveToPoint: NSMakePoint(6.16, 13.24) controlPoint1: NSMakePoint(6.51, 13.12) controlPoint2: NSMakePoint(6.33, 13.24)];
        [bezier15Path curveToPoint: NSMakePoint(5.82, 12.99) controlPoint1: NSMakePoint(5.99, 13.24) controlPoint2: NSMakePoint(5.82, 13.12)];
        [bezier15Path lineToPoint: NSMakePoint(5.59, 7.43)];
        [bezier15Path lineToPoint: NSMakePoint(5.82, 4.74)];
        [bezier15Path curveToPoint: NSMakePoint(6.16, 4.5) controlPoint1: NSMakePoint(5.82, 4.62) controlPoint2: NSMakePoint(5.99, 4.5)];
        [bezier15Path curveToPoint: NSMakePoint(6.51, 4.74) controlPoint1: NSMakePoint(6.33, 4.5) controlPoint2: NSMakePoint(6.51, 4.62)];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(8.86, 4.81)];
        [bezier15Path lineToPoint: NSMakePoint(9.09, 7.43)];
        [bezier15Path lineToPoint: NSMakePoint(8.86, 13.06)];
        [bezier15Path curveToPoint: NSMakePoint(8.51, 13.36) controlPoint1: NSMakePoint(8.86, 13.24) controlPoint2: NSMakePoint(8.69, 13.36)];
        [bezier15Path curveToPoint: NSMakePoint(8.17, 13.06) controlPoint1: NSMakePoint(8.28, 13.36) controlPoint2: NSMakePoint(8.17, 13.24)];
        [bezier15Path lineToPoint: NSMakePoint(8, 7.43)];
        [bezier15Path lineToPoint: NSMakePoint(8.17, 4.81)];
        [bezier15Path curveToPoint: NSMakePoint(8.51, 4.5) controlPoint1: NSMakePoint(8.17, 4.62) controlPoint2: NSMakePoint(8.34, 4.5)];
        [bezier15Path curveToPoint: NSMakePoint(8.86, 4.81) controlPoint1: NSMakePoint(8.69, 4.5) controlPoint2: NSMakePoint(8.86, 4.62)];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(11.15, 4.81)];
        [bezier15Path lineToPoint: NSMakePoint(11.32, 7.37)];
        [bezier15Path lineToPoint: NSMakePoint(11.15, 13.79)];
        [bezier15Path curveToPoint: NSMakePoint(10.75, 14.09) controlPoint1: NSMakePoint(11.15, 13.97) controlPoint2: NSMakePoint(10.98, 14.09)];
        [bezier15Path curveToPoint: NSMakePoint(10.35, 13.79) controlPoint1: NSMakePoint(10.52, 14.09) controlPoint2: NSMakePoint(10.35, 13.97)];
        [bezier15Path lineToPoint: NSMakePoint(10.18, 7.37)];
        [bezier15Path lineToPoint: NSMakePoint(10.35, 4.81)];
        [bezier15Path curveToPoint: NSMakePoint(10.75, 4.5) controlPoint1: NSMakePoint(10.35, 4.62) controlPoint2: NSMakePoint(10.52, 4.5)];
        [bezier15Path curveToPoint: NSMakePoint(11.15, 4.81) controlPoint1: NSMakePoint(10.98, 4.5) controlPoint2: NSMakePoint(11.15, 4.62)];
        [bezier15Path closePath];
        [bezier15Path moveToPoint: NSMakePoint(12.82, 4.5)];
        [bezier15Path curveToPoint: NSMakePoint(21.02, 4.5) controlPoint1: NSMakePoint(12.82, 4.5) controlPoint2: NSMakePoint(20.96, 4.5)];
        [bezier15Path curveToPoint: NSMakePoint(24, 7.62) controlPoint1: NSMakePoint(22.62, 4.5) controlPoint2: NSMakePoint(24, 5.91)];
        [bezier15Path curveToPoint: NSMakePoint(21.02, 10.73) controlPoint1: NSMakePoint(24, 9.33) controlPoint2: NSMakePoint(22.68, 10.73)];
        [bezier15Path curveToPoint: NSMakePoint(19.87, 10.49) controlPoint1: NSMakePoint(20.62, 10.73) controlPoint2: NSMakePoint(20.21, 10.67)];
        [bezier15Path curveToPoint: NSMakePoint(14.65, 15.5) controlPoint1: NSMakePoint(19.64, 13.3) controlPoint2: NSMakePoint(17.4, 15.5)];
        [bezier15Path curveToPoint: NSMakePoint(12.76, 15.13) controlPoint1: NSMakePoint(13.96, 15.5) controlPoint2: NSMakePoint(13.33, 15.38)];
        [bezier15Path curveToPoint: NSMakePoint(12.47, 14.77) controlPoint1: NSMakePoint(12.53, 15.07) controlPoint2: NSMakePoint(12.47, 14.95)];
        [bezier15Path lineToPoint: NSMakePoint(12.47, 4.87)];
        [bezier15Path curveToPoint: NSMakePoint(12.82, 4.5) controlPoint1: NSMakePoint(12.47, 4.68) controlPoint2: NSMakePoint(12.64, 4.5)];
        [bezier15Path closePath];
        [bezier15Path setMiterLimit: 4];
        [StreamCloudStyles.grayDark setFill];
        [bezier15Path fill];
    }
}

+ (void)drawImageOverlayGradientViewWithFrame: (NSRect)frame;
{
    //// Color Declarations
    NSColor* imageOverlayGradientColor = [NSColor colorWithCalibratedRed: 0 green: 0 blue: 0 alpha: 0.8];
    NSColor* imageOverlayGradientColor2 = [NSColor colorWithCalibratedRed: 0 green: 0 blue: 0 alpha: 0];

    //// Gradient Declarations
    NSGradient* imageOverlayGradient = [NSGradient.alloc initWithColorsAndLocations: 
        imageOverlayGradientColor, 0.0, 
        imageOverlayGradientColor2, 0.49, nil];

    //// Rectangle Drawing
    NSBezierPath* rectanglePath = [NSBezierPath bezierPathWithRect: NSMakeRect(NSMinX(frame), NSMinY(frame) + NSHeight(frame) - 320, 320, 320)];
    [imageOverlayGradient drawInBezierPath: rectanglePath angle: 90];
}

+ (void)drawVolumeSettingsWithFrame: (NSRect)frame volumeToShow: (CGFloat)volumeToShow;
{
    //// Color Declarations
    NSColor* fakeClearColor = [NSColor colorWithCalibratedRed: 1 green: 1 blue: 1 alpha: 0];

    //// Variable Declarations
    NSColor* colorForFirstWave = volumeToShow > 3 ? StreamCloudStyles.grayDark : fakeClearColor;
    NSColor* colorForSecondWave = volumeToShow > 37 ? StreamCloudStyles.grayDark : fakeClearColor;
    NSColor* colorForThirdWave = volumeToShow > 63 ? StreamCloudStyles.grayDark : fakeClearColor;


    //// Subframes
    NSRect group = NSMakeRect(NSMinX(frame), NSMinY(frame), NSWidth(frame), NSHeight(frame));


    //// Group
    {
        //// Bezier Drawing
        NSBezierPath* bezierPath = NSBezierPath.bezierPath;
        [bezierPath moveToPoint: NSMakePoint(NSMinX(group) + 0.77480 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.72650 * NSWidth(group), NSMinY(group) + 0.06842 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.92102 * NSWidth(group), NSMinY(group) + 0.49964 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.84465 * NSWidth(group), NSMinY(group) + 0.16821 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.92102 * NSWidth(group), NSMinY(group) + 0.32431 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.72650 * NSWidth(group), NSMinY(group) + 0.93158 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.92102 * NSWidth(group), NSMinY(group) + 0.67569 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.84465 * NSWidth(group), NSMinY(group) + 0.83108 * NSHeight(group))];
        [bezierPath lineToPoint: NSMakePoint(NSMinX(group) + 0.77480 * NSWidth(group), NSMinY(group) + 1.00000 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.50036 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.91188 * NSWidth(group), NSMinY(group) + 0.88453 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.70349 * NSHeight(group))];
        [bezierPath curveToPoint: NSMakePoint(NSMinX(group) + 0.77480 * NSWidth(group), NSMinY(group) + 0.00000 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 1.00000 * NSWidth(group), NSMinY(group) + 0.29579 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.91123 * NSWidth(group), NSMinY(group) + 0.11547 * NSHeight(group))];
        [bezierPath closePath];
        [bezierPath setMiterLimit: 4];
        [bezierPath setWindingRule: NSEvenOddWindingRule];
        [colorForThirdWave setFill];
        [bezierPath fill];


        //// Bezier 2 Drawing
        NSBezierPath* bezier2Path = NSBezierPath.bezierPath;
        [bezier2Path moveToPoint: NSMakePoint(NSMinX(group) + 0.67820 * NSWidth(group), NSMinY(group) + 0.13614 * NSHeight(group))];
        [bezier2Path lineToPoint: NSMakePoint(NSMinX(group) + 0.62990 * NSWidth(group), NSMinY(group) + 0.20456 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.76240 * NSWidth(group), NSMinY(group) + 0.49964 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.71084 * NSWidth(group), NSMinY(group) + 0.27299 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.76240 * NSWidth(group), NSMinY(group) + 0.37919 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.62924 * NSWidth(group), NSMinY(group) + 0.79544 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.76240 * NSWidth(group), NSMinY(group) + 0.62010 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.71018 * NSWidth(group), NSMinY(group) + 0.72701 * NSHeight(group))];
        [bezier2Path lineToPoint: NSMakePoint(NSMinX(group) + 0.67755 * NSWidth(group), NSMinY(group) + 0.86386 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.84138 * NSWidth(group), NSMinY(group) + 0.50036 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.77742 * NSWidth(group), NSMinY(group) + 0.77976 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.84138 * NSWidth(group), NSMinY(group) + 0.64861 * NSHeight(group))];
        [bezier2Path curveToPoint: NSMakePoint(NSMinX(group) + 0.67820 * NSWidth(group), NSMinY(group) + 0.13614 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.84204 * NSWidth(group), NSMinY(group) + 0.35139 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.77807 * NSWidth(group), NSMinY(group) + 0.22024 * NSHeight(group))];
        [bezier2Path closePath];
        [colorForSecondWave setFill];
        [bezier2Path fill];


        //// Bezier 3 Drawing
        NSBezierPath* bezier3Path = NSBezierPath.bezierPath;
        [bezier3Path moveToPoint: NSMakePoint(NSMinX(group) + 0.58225 * NSWidth(group), NSMinY(group) + 0.27299 * NSHeight(group))];
        [bezier3Path lineToPoint: NSMakePoint(NSMinX(group) + 0.53394 * NSWidth(group), NSMinY(group) + 0.34141 * NSHeight(group))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group) + 0.60574 * NSWidth(group), NSMinY(group) + 0.49964 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.57702 * NSWidth(group), NSMinY(group) + 0.37847 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.60574 * NSWidth(group), NSMinY(group) + 0.43478 * NSHeight(group))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group) + 0.53329 * NSWidth(group), NSMinY(group) + 0.65859 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.60574 * NSWidth(group), NSMinY(group) + 0.56450 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.57702 * NSWidth(group), NSMinY(group) + 0.62153 * NSHeight(group))];
        [bezier3Path lineToPoint: NSMakePoint(NSMinX(group) + 0.58159 * NSWidth(group), NSMinY(group) + 0.72701 * NSHeight(group))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group) + 0.68407 * NSWidth(group), NSMinY(group) + 0.49964 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.64426 * NSWidth(group), NSMinY(group) + 0.67427 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.68407 * NSWidth(group), NSMinY(group) + 0.59230 * NSHeight(group))];
        [bezier3Path curveToPoint: NSMakePoint(NSMinX(group) + 0.58225 * NSWidth(group), NSMinY(group) + 0.27299 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.68407 * NSWidth(group), NSMinY(group) + 0.40699 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.64426 * NSWidth(group), NSMinY(group) + 0.32502 * NSHeight(group))];
        [bezier3Path closePath];
        [colorForFirstWave setFill];
        [bezier3Path fill];


        //// Bezier 4 Drawing
        NSBezierPath* bezier4Path = NSBezierPath.bezierPath;
        [bezier4Path moveToPoint: NSMakePoint(NSMinX(group) + 0.05287 * NSWidth(group), NSMinY(group) + 0.26942 * NSHeight(group))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.32716 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.02350 * NSWidth(group), NSMinY(group) + 0.26942 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.29508 * NSHeight(group))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.67213 * NSHeight(group))];
        [bezier4Path curveToPoint: NSMakePoint(NSMinX(group) + 0.05287 * NSWidth(group), NSMinY(group) + 0.72986 * NSHeight(group)) controlPoint1: NSMakePoint(NSMinX(group) + 0.00000 * NSWidth(group), NSMinY(group) + 0.70421 * NSHeight(group)) controlPoint2: NSMakePoint(NSMinX(group) + 0.02350 * NSWidth(group), NSMinY(group) + 0.72986 * NSHeight(group))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group) + 0.26305 * NSWidth(group), NSMinY(group) + 0.72986 * NSHeight(group))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group) + 0.47389 * NSWidth(group), NSMinY(group) + 0.95937 * NSHeight(group))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group) + 0.47389 * NSWidth(group), NSMinY(group) + 0.03991 * NSHeight(group))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group) + 0.26371 * NSWidth(group), NSMinY(group) + 0.26942 * NSHeight(group))];
        [bezier4Path lineToPoint: NSMakePoint(NSMinX(group) + 0.05287 * NSWidth(group), NSMinY(group) + 0.26942 * NSHeight(group))];
        [bezier4Path closePath];
        [StreamCloudStyles.grayDark setFill];
        [bezier4Path fill];
    }
}

#pragma mark Generated Images

+ (NSImage*)imageOfPlayPauseButtonWithFrame: (NSRect)frame playing: (BOOL)playing;
{
    NSImage* imageOfPlayPauseButton = [NSImage.alloc initWithSize: NSMakeSize(48, 48)];
    [imageOfPlayPauseButton lockFocus];
    [StreamCloudStyles drawPlayPauseButtonWithFrame: frame playing: playing];
    [imageOfPlayPauseButton unlockFocus];

    return imageOfPlayPauseButton;
}

+ (NSImage*)imageOfShuffleButtonWithFrame: (NSRect)frame active: (BOOL)active;
{
    NSImage* imageOfShuffleButton = [NSImage.alloc initWithSize: NSMakeSize(32, 28)];
    [imageOfShuffleButton lockFocus];
    [StreamCloudStyles drawShuffleButtonWithFrame: frame active: active];
    [imageOfShuffleButton unlockFocus];

    return imageOfShuffleButton;
}

+ (NSImage*)imageOfRepeatButtonWithFrame: (NSRect)frame repeatMode: (CGFloat)repeatMode;
{
    NSImage* imageOfRepeatButton = [NSImage.alloc initWithSize: NSMakeSize(32, 30)];
    [imageOfRepeatButton lockFocus];
    [StreamCloudStyles drawRepeatButtonWithFrame: frame repeatMode: repeatMode];
    [imageOfRepeatButton unlockFocus];

    return imageOfRepeatButton;
}

+ (NSImage*)imageOfSoundCloudLogoWithFrame: (NSRect)frame;
{
    NSImage* imageOfSoundCloudLogo = [NSImage.alloc initWithSize: NSMakeSize(40, 18)];
    [imageOfSoundCloudLogo lockFocus];
    [StreamCloudStyles drawSoundCloudLogoWithFrame: frame];
    [imageOfSoundCloudLogo unlockFocus];

    return imageOfSoundCloudLogo;
}

+ (NSImage*)imageOfPlayingIndicatorWithFrame: (NSRect)frame;
{
    NSImage* imageOfPlayingIndicator = [NSImage.alloc initWithSize: NSMakeSize(240, 120)];
    [imageOfPlayingIndicator lockFocus];
    [StreamCloudStyles drawPlayingIndicatorWithFrame: frame];
    [imageOfPlayingIndicator unlockFocus];

    return imageOfPlayingIndicator;
}

+ (NSImage*)imageOfMenuBarIcon;
{
    if (_imageOfMenuBarIcon)
        return _imageOfMenuBarIcon;

    _imageOfMenuBarIcon = [NSImage.alloc initWithSize: NSMakeSize(25, 20)];
    [_imageOfMenuBarIcon lockFocus];
    [StreamCloudStyles drawMenuBarIcon];
    [_imageOfMenuBarIcon unlockFocus];

    return _imageOfMenuBarIcon;
}

+ (NSImage*)imageOfImageOverlayGradientViewWithFrame: (NSRect)frame;
{
    NSImage* imageOfImageOverlayGradientView = [NSImage.alloc initWithSize: NSMakeSize(320, 320)];
    [imageOfImageOverlayGradientView lockFocus];
    [StreamCloudStyles drawImageOverlayGradientViewWithFrame: frame];
    [imageOfImageOverlayGradientView unlockFocus];

    return imageOfImageOverlayGradientView;
}

@end
